language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
dist: trusty
sudo: false
script: gradle/buildViaTravis.sh
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
env:
  global:
  - secure: K2Wes5lFFJSwdYhH3T4yrIj2Vz6paEjNYFWBLCVXrw6YLrtih7QH1I80nnFmxtktkb70Lv0Dbz7vyakuGuMdo2EB/lU+v7Utzo0mAxpY7Vxy2z/KI7SdedUObXZ+7z7UW11upcGc7CU1GL4nQk8DQXzML5+fIeTckPwoMCNOHst4Bpy9rUixhvjBAH/N2hctyfcJ9ZbzB9KIC2d0ytHdA/tb+0ZoZjO37TZogUkirJ7ScpZLa7N5+MS3Ja+sauPOf32Tb8nL8kBgO2HygX+G3Tb1sP31lN6fCsxe8CLSWPULV1iqtP3eW8MayjUUo1B7rvq0wyUnqU3bcUlsVzhxOhbbtRg/G2OLhfro4Kl+eW1RZmJ6VSa5M/3W/wlExUeaxyt6C3YMpsaB9fsvgqIX8WJzthHjI5/tGx4IU6Z+xETC5KWVgBGlhfyOtCUTgwSJf9e3jr09nJEw6a5StVcesIFMZ9lCHhWg/iwzQaSS0X+nGIrrYDcuBIv4rfS4rQpDxxUtf3iMJUQ+7m5x7WrBs1jGlsa+eGui14CgH9aalh3MTfHF3CPrO7rGApiCYEVyLBt9HaKyfV9fUeBp/A644ye7JTqK8GPaL70CYM+ATYoginRyADDG2kW8kqmCKLNF3o3NxsiklsQJSA9awe5B201nXsjqPU9a1YByzOLJ4ic=
  - secure: m1/1hYVNnWhK4He8yWecKpWQAlLEBMwYHI6lLKELbczRK24dK2sYDCg+XnihtvZKtxIlfOim4Bsy/bpu1tQYUbz4ao4pUeyTZzU82dWM9nDzh5XavxobNIGBwG5ZJz57b6KJoBSzbYLvJpjdlMtziKLAMwe7iZ5InD1LKuEsiN7GLBjZSNKBrpUYXbwSQhF9+CgC+XKrB+VAFjvtGVfuaAZWy4vUvf92wfxfcAGUTKJUIysHfTVna66RtUBzp2pxscTUpEJ57H5GygjPL5y9n8WpOnJFGsPsJTgrUdIaM7FwHsWWoXpm+8vSsuBuLtFG/rtJbGoJTspQYENP7ULUAmF2m/sXfllyPGxzx8ARoxghO5PCND/DMC87v3sfENG2rbqCjQwzSn5gHiD6EO+v/Vur52uaM8ou0ZwBpARBVoJ+YiRSPK+T2YHAcnAqc/sAD0+uu7p8P8P8b9RNkRFN0IOTcr9BLovKzbmR3x0PvL5XUu08peJorpW63vK55P8h8qRoDWP59tdk8v57aW4LbFIGk+5VR+4ZT1RSjtfS7iXjnrqJjoW8hyHLdZudyy4fO7jnGbzM3uP22NC3ilvCUrmVhmnzh2IvVo/GqH0AE6tSbfaMVy8X7OfOHJ0MeLTPOvirYyLksSZlhd57MXqAWkknHn+hgdC2IKbe4EgXpdo=
