language: java
sudo: false
jdk:
- oraclejdk8
install: true
script: gradle/buildViaTravis.sh
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.m2
env:
  global:
  - secure: "k9ZDSoZeo3UXKnPH791dZlTa30ZrCaj7aNJ1VLTGWtmvPP4+MZn1Z95x/MfLc2GDHiHBnF0Bp51UB1QvAw3hXkZM7LS7fVEqkEHzVZf64oGVRA9mHrtWkBB7y7SRB+KCjksWHE0bSdHimpiPUHhiOR0P6P7LDFGKpXGADkIhTX/q2j+am4vHMGkGUTuwEQeMB6MC+rapNl7kvuWks2t9x+mkYEQd+jKNhQ1MAOUMBC4LzbiHFjiUfBOkCLvzNX8LK4gHFSgaUkoQT0OUpIqJ4a913k4yFyogZ3CwW2WwgdREJ56RvUQeB4kMTaqEg6K74KiZBfhfYQI82sGTvH892KKKjfUw2UKUcLxwlMJRNrlGXLZsCgA1ym/qTRvciNveplPP3cJkprVXnsjUp4X4sZe0KakSLhLaYCfa3cNlqnXUa0tJ+KYXeydwU/zfZ2YzvOO965boZ3ZCijk3FBF1wimTwZKxuXS/ughrgZ0xwtk9ITnRJhohLGjiOKvn9x8J9AH276jcgH+2rkdMaZDbtwaSd6Q2FmTRglvuoehLh21mMtLE1V+ctbmLDsAfpy3fetfY1+Pxc2ZfqBOpNU21Vy230FTR51nimGg6Soq+HsF7IH8U12nceDIufHp0tnWb0/CmBC0447evVnarUHsHv66BD2lbCZkW+enL9UYNfio="
  - secure: "jfjqbZsZ9XSt0HpHu8SAJLe2eqK2VHg67jSJ++Pg/ub33k0irwgwM/eY+1iLlbMbbJAefcYESlpToCll1rUoBHE9OOC2VVbv4ah+5E0NhGm78gSQO25XaMBJfWlOSoqKTvXLhLP2Az14HF3aPPtyjFwr7eauET3MUpozl2e+7lYojFJhrsxxcDJ492HqZybgb0od5Sq6FpP7/aljqyYx6i31MbrGWjdGeubVqf4d9P/CjmpvXJMzFwf9XQrG3SmQmayHOBvxtDKd602Vwuc8nU2hAFr102mX4TbhQJbHilLeJ+PcaEwhaIaDcDnp9wbeULdOLHWp6vIYAI7EMILD0rL1p4c/wKNz08hkKS7tk1F4DxlNPFNuAMl9yqp36aDsL7trc25Ept1QIMDLykBJ7VOdxeb4P/mRHOgSEv3kQGf/U5KYNVV0sSe4yWYobF4T95z6sj501zymqfLZCL9apI/5W+lHzGTpvFl9gglYKiP9dV4NUsgE96Rf+m0QKRKp+haxW7uDVubZLqkaBSNU5o9tILrccx7F4vP926HFdD4k53afxSosaP6JisX6QUEzMWC4tZX5t5yk/anaSOrOpYMcWbynhaECMjc/V0F/d36w1YxBML4u/e/ISgX0Kc+Kt+gAFdDQQ0b6o+P0RRqtyyRAEKmUu7DciM/3RIMHHfg="
